/**
 * Copyright (C) 2012 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileLoggerForm.java
 *
 * Created on 4 juil. 2012, 21:17:07
 */
package org.thingml.chestbelt.desktop;

import org.thingml.chestbelt.driver.ChestBelt;
//import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author franck
 */
public class WebServiceForm extends javax.swing.JFrame {

    JFileChooser chooser = new JFileChooser();
    Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
    ChestBelt belt;
    ChestBeltWebService webservice;
    OrientationCalculator orientationCalculator = null;
    
    
    
    public WebServiceForm(ChestBelt b) {
        this.belt = b;
        initComponents();
        //chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        //chooser.setMultiSelectionEnabled(false);
        //jTextFieldFolder.setText(prefs.get("LogFolder", ""));
        
    }
    
    public WebServiceForm(ChestBelt b, OrientationCalculator orientationCalculator) {
        this.belt = b;
        this.orientationCalculator = orientationCalculator;
        initComponents();
        //chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        //chooser.setMultiSelectionEnabled(false);
        //jTextFieldFolder.setText(prefs.get("LogFolder", ""));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRecord = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextGateway = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextSensor = new javax.swing.JTextField();
        jTextComputer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ChestBelt File Logger");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play-2.png"))); // NOI18N
        jButtonRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordActionPerformed(evt);
            }
        });

        jButtonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pause-2.png"))); // NOI18N
        jButtonStop.setEnabled(false);
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jTextField1.setText("http://visitest.imatiscloud.com/Imatis/WebServices/External/IntegrationService/IntegrationService.svc/web/Send");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextGateway.setText("99887766");
        jTextGateway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGatewayActionPerformed(evt);
            }
        });

        jLabel1.setText("GatewayId");

        jLabel2.setText("WebService url");

        jLabel3.setText("SensorId");

        jTextSensor.setText("Chestbelt");
        jTextSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSensorActionPerformed(evt);
            }
        });

        jTextComputer.setText("Chestbelt 13606");
        jTextComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextComputerActionPerformed(evt);
            }
        });

        jLabel4.setText("ComputerId");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRecord))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jTextGateway, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextGateway, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextComputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordActionPerformed
   String url = jTextField1.getText(); 
   String Gateway = jTextGateway.getText(); 
   String Sensor = jTextSensor.getText();
   String Computer = jTextComputer.getText();
   
    webservice = new ChestBeltWebService(url, Gateway, Sensor, Computer, belt);
    belt.addChestBeltListener(webservice);
    //if (orientationCalculator != null) orientationCalculator.addOrientationCalculatorListener(webservice);
        
    webservice.startLogging(); //Start web service
    jButtonRecord.setEnabled(false);
    jButtonStop.setEnabled(true);
}//GEN-LAST:event_jButtonRecordActionPerformed


private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
    if (webservice != null) {
        belt.removeChestBeltListener(webservice);
        webservice.stopLogging();
        webservice = null;
    }
    jButtonRecord.setEnabled(true);
    jButtonStop.setEnabled(false);
}//GEN-LAST:event_jButtonStopActionPerformed

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    if (webservice != null) {
        belt.removeChestBeltListener(webservice);
        webservice.stopLogging();
        webservice = null;
    }
}//GEN-LAST:event_formWindowClosed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextGatewayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGatewayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGatewayActionPerformed

    private void jTextSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSensorActionPerformed

    private void jTextComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextComputerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextComputerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextComputer;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextGateway;
    private javax.swing.JTextField jTextSensor;
    // End of variables declaration//GEN-END:variables
}
